# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=badnet --poison_rate=0.00 --patch_size=3 --moddir model_pt/badnet_ps7_pr0.01 --samdir train_sample/badnet_ps7_pr0.01 --save_data
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=badnet --poison_rate=0.01 --patch_size=7 --moddir model_pt/badnet_ps7_pr0.01 --samdir train_sample/badnet_ps7_pr0.01 --save_data
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=badnet --poison_rate=0.1 --patch_size=7 --moddir model_pt/badnet_ps7_pr0.1 --samdir train_sample/badnet_ps7_pr0.1

# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29402 --nproc_per_node=gpu train.py --moddir model_pt/clean --samdir train_sample/clean --save_data

# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29402 --nproc_per_node=gpu train.py --backdoor_type=badnet --target_label=0 --poison_rate=0.01 --patch_size=5 --moddir model_pt/badnet_ps5_pr0.01 --samdir train_sample/badnet_ps5_pr0.01 --save_data
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29402 --nproc_per_node=gpu train.py --backdoor_type=badnet --target_label=0 --poison_rate=0.05 --patch_size=5 --moddir model_pt/badnet_ps5_pr0.05 --samdir train_sample/badnet_ps5_pr0.05 --save_data
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29402 --nproc_per_node=gpu train.py --backdoor_type=badnet --target_label=0 --poison_rate=0.1 --patch_size=5 --moddir model_pt/badnet_ps5_pr0.1 --samdir train_sample/badnet_ps5_pr0.1 --save_data
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29402 --nproc_per_node=gpu train.py --backdoor_type=badnet --target_label=0 --poison_rate=0.01 --patch_size=7 --moddir model_pt/badnet_ps7_pr0.01 --samdir train_sample/badnet_ps7_pr0.01 --save_data
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29402 --nproc_per_node=gpu train.py --backdoor_type=badnet --target_label=0 --poison_rate=0.05 --patch_size=7 --moddir model_pt/badnet_ps7_pr0.05 --samdir train_sample/badnet_ps7_pr0.05 --save_data
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29402 --nproc_per_node=gpu train.py --backdoor_type=badnet --target_label=0 --poison_rate=0.1 --patch_size=7 --moddir model_pt/badnet_ps7_pr0.1 --samdir train_sample/badnet_ps7_pr0.1 --save_data

# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.01 --target_label=0 --moddir model_pt/trojan_pr0.01_tgt0 --samdir train_sample/trojan_pr0.01_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.05 --target_label=0 --moddir model_pt/trojan_pr0.05_tgt0 --samdir train_sample/trojan_pr0.05_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.1 --target_label=0 --moddir model_pt/trojan_pr0.1_tgt0 --samdir train_sample/trojan_pr0.1_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.01 --target_label=4 --moddir model_pt/trojan_pr0.01_tgt4 --samdir train_sample/trojan_pr0.01_tgt4
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.05 --target_label=4 --moddir model_pt/trojan_pr0.05_tgt4 --samdir train_sample/trojan_pr0.05_tgt4
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.1 --target_label=4 --moddir model_pt/trojan_pr0.1_tgt4 --samdir train_sample/trojan_pr0.1_tgt4


# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=badnet --poison_rate=0.01 --patch_size=5 --target_label=0 --moddir model_pt2/badnet_ps5_pr0.01_tgt0 --samdir train_sample2/badnet_ps5_pr0.01_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=badnet --poison_rate=0.05 --patch_size=5 --target_label=0 --moddir model_pt2/badnet_ps5_pr0.05_tgt0 --samdir train_sample2/badnet_ps5_pr0.05_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=badnet --poison_rate=0.1 --patch_size=5 --target_label=0 --moddir model_pt2/badnet_ps5_pr0.1_tgt0 --samdir train_sample2/badnet_ps5_pr0.1_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=badnet --poison_rate=0.01 --patch_size=5 --target_label=4 --moddir model_pt2/badnet_ps5_pr0.01_tgt4 --samdir train_sample2/badnet_ps5_pr0.01_tgt4
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=badnet --poison_rate=0.05 --patch_size=5 --target_label=4 --moddir model_pt2/badnet_ps5_pr0.05_tgt4 --samdir train_sample2/badnet_ps5_pr0.05_tgt4
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=badnet --poison_rate=0.1 --patch_size=5 --target_label=4 --moddir model_pt2/badnet_ps5_pr0.1_tgt4 --samdir train_sample2/badnet_ps5_pr0.1_tgt4

# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.05 --target_label=0 --moddir model_pt2/trojan_pr0.05_tgt0 --samdir train_sample2/trojan_pr0.05_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.1 --target_label=0 --moddir model_pt2/trojan_pr0.1_tgt0 --samdir train_sample2/trojan_pr0.1_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.01 --target_label=0 --moddir model_pt2/trojan_pr0.01_tgt0 --samdir train_sample2/trojan_pr0.01_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.05 --target_label=4 --moddir model_pt2/trojan_pr0.05_tgt4 --samdir train_sample2/trojan_pr0.05_tgt4
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.1 --target_label=4 --moddir model_pt2/trojan_pr0.1_tgt4 --samdir train_sample2/trojan_pr0.1_tgt4
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=trojan --poison_rate=0.01 --target_label=4 --moddir model_pt2/trojan_pr0.01_tgt4 --samdir train_sample2/trojan_pr0.01_tgt4

# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=blend --poison_rate=0.1 --target_label=0 --moddir model_pt2/blend_pr0.1_tgt0 --samdir train_sample2/blend_pr0.1_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=blend --poison_rate=0.01 --target_label=0 --moddir model_pt2/blend_pr0.01_tgt0 --samdir train_sample2/blend_pr0.01_tgt0
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=blend --poison_rate=0.1 --target_label=4 --moddir model_pt2/blend_pr0.1_tgt4 --samdir train_sample2/blend_pr0.1_tgt4
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --backdoor_type=blend --poison_rate=0.01 --target_label=4 --moddir model_pt2/blend_pr0.01_tgt4 --samdir train_sample2/blend_pr0.01_tgt4


# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --poison_data_path ../data/CIFAR10/poison/badnet_ps5_pr0.01_pt4.npz  --moddir model_ckpt/badnet_ps5_pr0.01_pt4 --samdir train_sample/badnet_ps5_pr0.01_pt4
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --poison_data_path ../data/CIFAR10/poison/badnet_ps5_pr0.05_pt4.npz --moddir model_ckpt/badnet_ps5_pr0.05_pt4 --samdir train_sample/badnet_ps5_pr0.05_pt4
# CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --poison_data_path ../data/CIFAR10/poison/badnet_ps5_pr0.1_pt4.npz --moddir model_ckpt/badnet_ps5_pr0.1_pt4 --samdir train_sample/badnet_ps5_pr0.1_pt4

CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --poison_data_path ../data/CIFAR10/poison/blend_pr0.01_pt4.npz  --moddir model_ckpt/blend_pr0.01_pt4 --samdir train_sample/blend_pr0.01_pt4
CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --poison_data_path ../data/CIFAR10/poison/blend_pr0.05_pt4.npz --moddir model_ckpt/blend_pr0.05_pt4 --samdir train_sample/blend_pr0.05_pt4
CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --rdzv-backend=c10d --rdzv-endpoint=localhost:29401 --nproc_per_node=gpu train.py --poison_data_path ../data/CIFAR10/poison/blend_pr0.1_pt4.npz --moddir model_ckpt/blend_pr0.1_pt4 --samdir train_sample/blend_pr0.1_pt4